stages:
  - build
  - release

sqler-build:
  stage: build
  tags:
    - tmp
  only:
    - dev
  script:
    - make build-win
    - make build-linux

sqler-release:
  stage: release
  only:
    - dev
  script:
    - release-cli create --name "Release $CI_COMMIT_SHA" --description \
      "Created using the release-cli $EXTRA_DESCRIPTION" \
      --tag-name "v${CI_COMMIT_SHORT_SHA}" --ref "$CI_COMMIT_SHA" \
      --assets-link "{\"name\":\"asset1\", \"filepath\":\"${CI_PROJECT_DIR}/bin/sqler.exe\", \"url\":\"https://example.com/assets/1\",\"link_type\":\"other\"}
