stages:
  - build
  - release

sqler-build:
  stage: build
  tags:
    - tmp
  only:
    - dev
  script:
    - make build-win
    - make build-linux

sqler-release:
  stage: release
  only:
    - dev
  release:
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'sqler.exe'
          filepath: 'bin/sqler.exe'
        - name: 'sqler'
          filepath: 'bin/sqler'