dataSourceArgs: collation=utf8mb4_general_ci&multiStatements=true&multiStatements=true
dataSources:
  - type: sqlite3
    url:
    schema: db_base
    username: root
    password: root
    enabled: true
  - type: sqlite3
    url:
    schema: db_01
    username: root
    password: root
    enabled: true
  - type: sqlite3
    url:
    schema: db_02
    username: root
    password: root
    enabled: true
commands:
  count-schemas:
    - a
    - b
  bdiff-schemas:
    - a
    - b
  bdiff-skip-cols:
    - update_date
    - create_date
    - a3