dataSourceArgs: collation=utf8mb4_general_ci&multiStatements=true&multiStatements=true
dataSources:
  - type: mysql
    url: 127.0.0.1:3307
    schema: db_base
    username: root
    password: root
    enabled: true
  - type: mysql
    url: 127.0.0.1:3308
    schema: db_01
    username: root
    password: root
    enabled: true
  - type: mysql
    url: 127.0.0.1:3309
    schema: db_02
    username: root
    password: root
    enabled: true
commands:
  count-schemas:
    - t1
    - t2
  bdiff-schemas:
    - a
    - b
    - c