dataSourceArgs: collation=utf8mb4_general_ci&multiStatements=true&multiStatements=true
dataSources:
    - type: mysql
      url: 127.0.0.1:3307
      schema: sqler_demo
      username: root
      password: root
      enabled: true
    - type: mysql
      url: 127.0.0.1:3308
      schema: sqler_demo
      username: root
      password: root
      enabled: true
    - type: mysql
      url: 127.0.0.1:3309
      schema: sqler_demo
      username: root
      password: root
      enabled: true
